FROM python:3.10
WORKDIR /app
COPY app/ /app
RUN pip install --upgrade pip && \
    pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu && \
    pip install flask && \
    pip install psycopg2-binary
EXPOSE 5000
CMD python ./app.py